'use client';

import { createClient } from '@/utils/supabase/client';

export async function updateProfile(data: {
    date_of_birth?: string;
    country_of_residence?: string;
}) {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) throw new Error('Unauthorized');

    const { error } = await supabase
        .from('profiles')
        .update({
            ...data,
            updated_at: new Date().toISOString()
        })
        .eq('id', user.id);

    if (error) {
        console.error('Error updating profile:', error);
        throw new Error(error.message);
    }

    return { success: true };
}

/**
 * Ensures the user has a student ID. If missing, it will be generated by the DB trigger
 * on the next profile update, but we can also trigger it manually if needed.
 */
export async function ensureStudentId() {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) throw new Error('Unauthorized');

    const { data: profile } = await supabase
        .from('profiles')
        .select('student_id')
        .eq('id', user.id)
        .single();

    if (!profile?.student_id) {
        // A simple update will trigger the student_id generation if it's currently null
        // according to the database trigger logic (if applied).
        const { error } = await supabase
            .from('profiles')
            .update({ updated_at: new Date().toISOString() })
            .eq('id', user.id);

        if (error) throw error;

        const { data: updatedProfile } = await supabase
            .from('profiles')
            .select('student_id')
            .eq('id', user.id)
            .single();

        return { studentId: updatedProfile?.student_id };
    }

    return { studentId: profile.student_id };
}
